### PR TITLE
Find all installed bots

### PR DESCRIPTION
**Pull request by musketyr**
This PR adds a method into `InstallationService` to list all the installed bots . See #1055 for further Information.

### Category (place an `x` in each of the `[ ]`)

* [x] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### CODE REVIEW

**Comment by seratch** [comment]
Hi @musketyr, thanks for sending this PR! However, we are not planning to add this method to the interface. Please consider having your own sub-class of `AmazonS3InstallationService` with the additional method plus using its instance in your listener methods.

**Comment by musketyr** [comment]
if you agree on this addition, I can add test using [Testcontainers with Localstack](https://www.testcontainers.org/modules/localstack/) for the Amazon S3 implementation.

**Comment by musketyr** [comment]
@seratch ok, this is quite a pity because it would make more sense to have the the ability directly in the library.

**Comment by seratch** [comment]
@musketyr Unfortunately, I don't think that this is a common scenario in many Slack apps while the find-all method can be useful for you. I'd appreciate it if you could understand our stance on maintaining this SDK here.

**Pull request closed without merging**
