### PR TITLE
Removing overriding of enterprise_id over team_id

### PR DESCRIPTION
**Pull request by gaurav2493**
## [Issue #378](https://github.com/slackapi/java-slack-sdk/issues/378)
teamId was getting overriden by enterprise id.
This behaviour is fixed int this commit

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by seratch** [comment]
@gaurav2493 Hello, thank you very much for taking the time to make this pull request. As the bot mentioned above, could you sign our CLA? Once you've signed it, we can merge this PR!
https://cla-assistant.io/slackapi/java-slack-sdk?pullRequest=379

**Comment by gaurav2493** [comment]
> @gaurav2493 Hello, thank you very much for taking the time to make this pull request. As the bot mentioned above, could you sign our CLA? Once you've signed it, we can merge this PR!
> https://cla-assistant.io/slackapi/java-slack-sdk?pullRequest=379

@seratch Yes I have signed it. Don't know why it's not showing here.
Screenshot 2020-03-06 at 9 55 53 AM

**Comment by gaurav2493** [comment]
> > @gaurav2493 Hello, thank you very much for taking the time to make this pull request. As the bot mentioned above, could you sign our CLA? Once you've signed it, we can merge this PR!
> > https://cla-assistant.io/slackapi/java-slack-sdk?pullRequest=379
> 
> @seratch Yes I have signed it. Don't know why it's not showing here.
> Screenshot 2020-03-06 at 9 55 53 AM

Just figured out that email id of my commit didn't match the email of github account

**Comment by gaurav2493** [comment]
> @gaurav2493 Hello, thank you very much for taking the time to make this pull request. As the bot mentioned above, could you sign our CLA? Once you've signed it, we can merge this PR!
> https://cla-assistant.io/slackapi/java-slack-sdk?pullRequest=379

Hi @seratch the email through which I had signed in was different from the commit author email due to which it was not showing as signed. Now it's fixed.

**Comment by seratch** [comment]
@gaurav2493 Thanks!

**Comment by seratch** [comment]
@gaurav2493 I just released version 1.0.0-RC1 onto the Maven Central repositories. Please try it out!

**Pull request merged**
