### PR TITLE
Docs: adds docusaurus site

### PR DESCRIPTION
**Pull request by lukegalbraithrussell**
## Summary

This PR adds a Docusaurus site. Tested that it builds properly. This is all done in the same way as the other sites site. 

https://github.com/user-attachments/assets/f6319792-48d9-4d5e-a6ad-b878f5f570ea

14,569 of those line changes are from `package-lock.json`. So it's really a +1900 change

If you've looked at the previous PRs, it's all pretty similar, with the exception of `docs/version-config.yml` and its use in `.workflows/doc-deploy`. 

You'll see placeholders in markdown files for version values. For example: `sdkLatestVersion`. The github workflow replaces these placeholders with the values set in `docs/version-config.yml`. The `sdkLatestVersion` value is set via `scripts/set_version.sh` but the other values are changed directly in the file.  When a value in `version-config.yml` is changed, the site is rebuilt automatically due to the github workflow looking for changes to `/docs`.  I tested this all out on my personal deployed docusaurus test site.

Anyway, there are about only a few files in this PR that matter for review. 

Maintenance files:

- [.scripts/set_version.sh](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-5d53315446330c949d6008adb306b9d8e74a2379a80e8b717b1ad106cf51715b) Changed the path of the yml file to update
- [.github/maintainers_guide.md](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-64710ddf9131ee0621e674aba34707aa85cca5f735c2c9421a7b6a57724e264e). I added a section linking to the docs README
- [.github/pull_request_template.md](). Removed script reference
- [.workflows/docs-deploy.yml](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-c60abbc0f5cbeb895e12237cf346049cff69c54024b84e9214b014e999472e58) Deploys site on merge, tests on PR
- [docs/README.md](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938) All the instructions
- [docs/version-config.yml](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-a1b6a2bea47e916cd0c759086a32d373827ba09e61fd2a647203201802216911) All the instructions

Site config files:
- [docs/babel.config.js](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-2ed4f5b03d34a87ef641e9e36af4a98a1c0ddaf74d07ce93665957be69b7b09a) This file exists and that’s about it
- [docs/docusaurus.config.js](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-28742c737e523f302e6de471b7fc27284dc8cf720be639e6afe4c17a550cd654) The main config file. Also where topbar and footer are set.
- [docs/package.json](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56) The packages
- [/docs/sidebar.js](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-e8aa23ec31a264f87ba92ce3eef2133d44d0190ec08ac6d6eba4913d031294e9) Sets the docs sidebar nav
- [/docs/src/css/custom.css](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-bba10eb4bb3b6b325f2e0cd219ae2fbd90e095dfb458f024d96f8406dff3ae5e) The CSS - matches homepage.

The 404 page has two files, for Docusaurus ~ reasons ~
- [/docs/theme/NotFound/Content/index](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-ab602d3226a5afe136dd3e8653b918a31c02a4de6a63a122b4bcf40d952676a1) The words
- [/docs/theme/NotFound/index](https://github.com/slackapi/java-slack-sdk/pull/1342/files#diff-f7311e20e5bd6fcc03edfea20606038a6e675f27e0f02793b4f959a70264f47e) The page the words go into

#### Folder and file organization

This shares the same structure as the other sites. At large:

```
java-slack-sdk/
├── .github/
│   └── workflows/
│       └── deploy.yaml (deploys to site, and inserts values from version-config.yml)
├── docs/ (the good stuff. md/mdx files supported)
│   ├── index.md
│   └── guides
│       └── bolt-basics.md
├── i18n/ja-jp/ (the japanese translations)
│   ├── docusaurus-theme-classic/ (footer/navbar translations)
│   └── docusaurus-plugin-content-docs/
│       └── current/ ( file names need to exactly match **/docs/, but japanese content)
│           ├── index.md
│           └── guides
│               └── bolt-basics.md
├── static/
│   ├── css/
│   │   └── custom.css (the css for everything!)
│   ├── img/ (the pictures for the site)
│   │   ├── rory.png 
│   │   └── oslo.svg  
├── src/
│   ├── pages/ (stuff that isn't docs. This is empty for this repo!)
│   └── theme/ (only contains the 404 page)
├── version-config.yml (Where version numbers are set)
├── docusaurus.config.js (main config file. also where to set navbar/footer)
└── sidebar.js (manually set where the docs are in the sidebar.)
```

#### Docs pages: slugs and links

The organization of pages is purposefully kept as similar to the current layout of pages so developers don't get jarred from both a site change and page changes. Slugs are all named matching that previous organization. URLs stay the same for the English site. 

The Japanese site unfortunately has to have slightly different slugs - they were at `/guides/ja/page` and docusaurus does `/ja/guides/page`.  At that point, I changed it to `/ja-jp/guides/pages` to match the other sites. I've added redirects, but they may need to toggle the language once redirected.

All `.md` files were renamed to match the title and the slug. Everything now matches up. 

All markdown reference links were also updated to be up-to-date and working. If it's a link on the site, it now works. They should all be the most basic of markdown now. 

#### Editing and managing the site

The README contains a basic docs editing guide. You don't need to worry about the site unless you're touching something inside the `/docs` folder. 

There is a new action workflow: it does a test build on docs PRs and deploys the site on merges to main. It does so also on every release so the generated reference docs stay up-to-date

#### Next steps

This wouldn't be a DevRel project without some fast follows. This is what I plan on doing after all the sites are live:
* Set up action workflow to update this `custom.css` if the main site's `custom.css` is changed.
* General copy editing (I avoided this the best I could in this PR).

### Testing

You can run the site locally:

`npm install`

`npm run start`

You can build and serve on your computer to swap between english and japanese:

`npm run build`

`npm run serve`

Click around! have fun! 

### Category
Just docs
## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### CODE REVIEW

**Comment by lukegalbraithrussell** [comment]
@seratch Nice catch! For some reason Java highlighting isn't enabled by default in Docusaurus. I've added the syntax highlighting for both Java and Groovy

**Comment by seratch** [comment]
@lukegalbraithrussell Thanks for quickly resolving it! 

With the latest revision, the only remaining issue I found is /image/* file access error. For example, `img/bolt-middleware.png` access from `http://localhost:3000/java-slack-sdk/guides/bolt-basics` returns not found HTML page instead of the png file. Can I ask you to identify the cause?

**Comment by lukegalbraithrussell** [comment]
@seratch The pictures are now working. Those shortened  `/img/path` file paths (instead of `/docs/static/img/path`) only work in markdown it seems. I switched it to markdown!

**Review by seratch — APPROVED** [review]
Thanks for quickly fixing the issue! LGTM now

**Pull request merged**
